package portregistry

import (
	"testing"

	"github.com/stretchr/testify/require"
)

var (
	dtrainSSHPortBase              = 12350
	interTrainProcessCommPort1Base = 12360
	interTrainProcessCommPort2Base = 12365
	c10DPortBase                   = 29400
)

func TestPortportRegistry(t *testing.T) {
	NewPortRegistry()
	port, err := GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12350, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12351, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12352, port)
	deleted := ReleasePort(12351)
	require.True(t, deleted)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12351, port)
	port, err = GetPort(c10DPortBase)
	require.NoError(t, err)
	require.Equal(t, 29400, port)
	port, err = GetPort(c10DPortBase)
	require.NoError(t, err)
	require.Equal(t, 29401, port)
	deleted = ReleasePort(12350)
	require.True(t, deleted)
	deleted = ReleasePort(12351)
	require.True(t, deleted)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12350, port)
	port, err = GetPort(c10DPortBase)
	require.NoError(t, err)
	require.Equal(t, 29402, port)
	port, err = GetPort(c10DPortBase)
	require.NoError(t, err)
	require.Equal(t, 29403, port)
	port, err = GetPort(interTrainProcessCommPort1Base)
	require.NoError(t, err)
	require.Equal(t, 12360, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12351, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12353, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12354, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12355, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12356, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12357, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12358, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12359, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12361, port)
	port, err = GetPort(interTrainProcessCommPort1Base)
	require.NoError(t, err)
	require.Equal(t, 12362, port)
	port, err = GetPort(interTrainProcessCommPort2Base)
	require.NoError(t, err)
	require.Equal(t, 12365, port)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12363, port)
	deleted = ReleasePort(12363)
	require.True(t, deleted)
	RestorePort(12363)
	port, err = GetPort(dtrainSSHPortBase)
	require.NoError(t, err)
	require.Equal(t, 12364, port)
	port, err = GetPort(interTrainProcessCommPort2Base)
	require.NoError(t, err)
	require.Equal(t, 12366, port)
	deleted = ReleasePort(12365)
	require.True(t, deleted)
	port, err = GetPort(interTrainProcessCommPort2Base)
	require.NoError(t, err)
	require.Equal(t, 12365, port)
}
