-- keeping out of the migration directory for now to avoid having it run
ALTER table trials ADD COLUMN IF NOT EXISTS tags jsonb;
CREATE INDEX trials_tags_index ON trials USING GIN (tags);
update trials set tags = '{}';

CREATE TABLE trials_collections (
-- table to store a set of filters as defined in QueryFilters in api/trial.proto
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,	
     user_id integer REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
	name text NOT NULL,
	filters jsonb,
  CONSTRAINT user_filter_name_uniq UNIQUE (user_id, name)
);

-- make analogous modifications to those found in reindex-steps pr
CREATE INDEX validations_archived ON raw_validations(archived);
ALTER TABLE raw_validations DROP CONSTRAINT validations_trial_id_run_id_total_batches_unique;
CREATE UNIQUE INDEX steps_trial_id_total_batches_run_id_unique ON raw_validations(trial_id, total_batches, trial_run_id);