build:
	GOOS=linux GOARCH=amd64 go build -o orchestrator.amd64 ./cmd/orchestrator
	GOOS=linux GOARCH=arm64 go build -o orchestrator.arm64 ./cmd/orchestrator
	GOOS=linux GOARCH=ppc64 go build -o orchestrator.ppc64 ./cmd/orchestrator
