-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DetQL.Object.Agent_user_groups_max_fields exposing (..)

import CustomScalarCodecs
import DetQL.InputObject
import DetQL.Interface
import DetQL.Object
import DetQL.Scalar
import DetQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


gid : SelectionSet (Maybe Int) DetQL.Object.Agent_user_groups_max_fields
gid =
    Object.selectionForField "(Maybe Int)" "gid" [] (Decode.int |> Decode.nullable)


group_ : SelectionSet (Maybe String) DetQL.Object.Agent_user_groups_max_fields
group_ =
    Object.selectionForField "(Maybe String)" "group_" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Int) DetQL.Object.Agent_user_groups_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


uid : SelectionSet (Maybe Int) DetQL.Object.Agent_user_groups_max_fields
uid =
    Object.selectionForField "(Maybe Int)" "uid" [] (Decode.int |> Decode.nullable)


user_ : SelectionSet (Maybe String) DetQL.Object.Agent_user_groups_max_fields
user_ =
    Object.selectionForField "(Maybe String)" "user_" [] (Decode.string |> Decode.nullable)


user_id : SelectionSet (Maybe Int) DetQL.Object.Agent_user_groups_max_fields
user_id =
    Object.selectionForField "(Maybe Int)" "user_id" [] (Decode.int |> Decode.nullable)
