-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DetQL.Object.Validation_metrics_max_fields exposing (..)

import CustomScalarCodecs
import DetQL.InputObject
import DetQL.Interface
import DetQL.Object
import DetQL.Scalar
import DetQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe Int) DetQL.Object.Validation_metrics_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


raw : SelectionSet (Maybe CustomScalarCodecs.Float8) DetQL.Object.Validation_metrics_max_fields
raw =
    Object.selectionForField "(Maybe CustomScalarCodecs.Float8)" "raw" [] (CustomScalarCodecs.codecs |> DetQL.Scalar.unwrapCodecs |> .codecFloat8 |> .decoder |> Decode.nullable)


signed : SelectionSet (Maybe CustomScalarCodecs.Float8) DetQL.Object.Validation_metrics_max_fields
signed =
    Object.selectionForField "(Maybe CustomScalarCodecs.Float8)" "signed" [] (CustomScalarCodecs.codecs |> DetQL.Scalar.unwrapCodecs |> .codecFloat8 |> .decoder |> Decode.nullable)
