package portoffsetregistry

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPortOffsetRegistry(t *testing.T) {
	NewPortOffsetRegistry()
	offset, err := GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 0, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 1, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 2, offset)
	deleted := ReleasePortOffset(1)
	require.True(t, deleted)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 1, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 3, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 4, offset)
	deleted = ReleasePortOffset(0)
	require.True(t, deleted)
	deleted = ReleasePortOffset(4)
	require.True(t, deleted)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 0, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 4, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 5, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 6, offset)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 7, offset)
	deleted = ReleasePortOffset(2)
	require.True(t, deleted)
	deleted = ReleasePortOffset(1)
	require.True(t, deleted)
	deleted = ReleasePortOffset(3)
	require.True(t, deleted)
	offset, err = GetPortOffset()
	require.NoError(t, err)
	require.Equal(t, 1, offset)
	fmt.Println("in here hi")
}
