ALTER TABLE workspaces ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE workspaces ALTER COLUMN archived SET DEFAULT NULL;

ALTER TABLE projects ALTER COLUMN archived DROP NOT NULL;
ALTER TABLE projects ALTER COLUMN archived SET DEFAULT NULL;
