DROP TABLE exp_hyperparameters;
DROP TABLE exp_metrics_name;

DROP TRIGGER autoupdate_exp_hyperparameters ON experiments;
DROP TRIGGER autoupdate_exp_training_metrics_name ON raw_steps;
DROP TRIGGER autoupdate_exp_validation_metrics_name ON raw_validations;

DROP FUNCTION autoupdate_exp_hyperparameters;
DROP FUNCTION autoupdate_exp_training_metrics_name;
DROP FUNCTION autoupdate_exp_validation_metrics_name;
