CREATE TYPE token_type AS ENUM ('USER_SESSION', 'ACCESS_TOKEN');

ALTER TABLE user_sessions ADD COLUMN created_at TIMESTAMP DEFAULT NULL;
ALTER TABLE user_sessions ADD COLUMN token_type token_type NOT NULL DEFAULT 'USER_SESSION';
ALTER TABLE user_sessions ADD COLUMN revoked_at TIMESTAMP DEFAULT NULL;
ALTER TABLE user_sessions ADD COLUMN description TEXT DEFAULT NULL;
