package expconf

// These dummy types let us compile the generated code without the real struct definitions present.
type (
	AdaptiveASHAConfigV0        struct{}
	AdaptiveConfigV0            struct{}
	AdaptiveSimpleConfigV0      struct{}
	AsyncHalvingConfigV0        struct{}
	BindMountV0                 struct{}
	CategoricalHyperparameterV0 struct{}
	CheckpointStorageConfigV0   struct{}
	ConstHyperparameterV0       struct{}
	DataLayerConfigV0           struct{}
	DoubleHyperparameterV0      struct{}
	EnvironmentConfigV0         struct{}
	EnvironmentImageMapV0       struct{}
	EnvironmentImageV0          struct{}
	EnvironmentVariablesMapV0   struct{}
	EnvironmentVariablesV0      struct{}
	ExperimentConfigV0          struct{}
	GCSConfigV0                 struct{}
	GCSDataLayerConfigV0        struct{}
	GridConfigV0                struct{}
	HDFSConfigV0                struct{}
	HyperparametersV0           struct{}
	HyperparameterV0            struct{}
	InternalConfigV0            struct{}
	IntHyperparameterV0         struct{}
	KerberosConfigV0            struct{}
	LengthV0                    struct{}
	LogHyperparameterV0         struct{}
	NativeConfigV0              struct{}
	OptimizationsConfigV0       struct{}
	PBTConfigV0                 struct{}
	RandomConfigV0              struct{}
	ReproducibilityConfigV0     struct{}
	ResourcesConfigV0           struct{}
	S3ConfigV0                  struct{}
	S3DataLayerConfigV0         struct{}
	SearcherConfigV0            struct{}
	SecurityConfigV0            struct{}
	SharedFSConfigV0            struct{}
	SharedFSDataLayerConfigV0   struct{}
	SingleConfigV0              struct{}
	SyncHalvingConfigV0         struct{}
	TensorboardStorageConfigV0  struct{}
)
