package expconf

// These dummy types let us compile the generated code without the real struct definitions present.
type (
	BindMountV0                    struct{}
	CheckpointStorageConfigV0      struct{}
	DataLayerGCSConfigV0           struct{}
	DataLayerS3ConfigV0            struct{}
	DataLayerSharedFSConfigV0      struct{}
	DataLayerConfigV0              struct{}
	EnvironmentImageV0             struct{}
	EnvironmentVariablesV0         struct{}
	EnvironmentConfigV0            struct{}
	ExperimentConfigV0             struct{}
	GCSConfigV0                    struct{}
	HDFSConfigV0                   struct{}
	CategoricalHyperparameterV0    struct{}
	ConstHyperparameterV0          struct{}
	DoubleHyperparameterV0         struct{}
	IntHyperparameterV0            struct{}
	LogHyperparameterV0            struct{}
	HyperparameterV0               struct{}
	InternalConfigV0               struct{}
	LengthV0                       struct{}
	OptimizationsConfigV0          struct{}
	ResourcesConfigV0              struct{}
	S3ConfigV0                     struct{}
	AdaptiveASHASearcherConfigV0   struct{}
	AdaptiveSimpleSearcherConfigV0 struct{}
	AdaptiveSearcherConfigV0       struct{}
	AsyncHalvingSearcherConfigV0   struct{}
	GridSearcherConfigV0           struct{}
	PBTSearcherConfigV0            struct{}
	RandomSearcherConfigV0         struct{}
	SingleSearcherConfigV0         struct{}
	SyncHalvingSearcherConfigV0    struct{}
	SearcherConfigV0               struct{}
	SharedFSConfigV0               struct{}
)
