// Code generated by gen.py. DO NOT EDIT.

package expconf

import (
	"github.com/santhosh-tekuri/jsonschema/v2"

	"github.com/determined-ai/determined/master/pkg/schemas"
)

func (s SlurmClusterConfigV0) SlotsPerNode() int {
	if s.RawSlotsPerNode == nil {
		panic("You must call WithDefaults on SlurmClusterConfigV0 before .SlotsPerNode")
	}
	return *s.RawSlotsPerNode
}

func (s *SlurmClusterConfigV0) SetSlotsPerNode(val int) {
	s.RawSlotsPerNode = &val
}

func (s SlurmClusterConfigV0) SbatchArgs() []string {
	return s.RawSbatchArgs
}

func (s *SlurmClusterConfigV0) SetSbatchArgs(val []string) {
	s.RawSbatchArgs = val
}

func (s SlurmClusterConfigV0) ParsedSchema() interface{} {
	return schemas.ParsedSlurmClusterConfigV0()
}

func (s SlurmClusterConfigV0) SanityValidator() *jsonschema.Schema {
	return schemas.GetSanityValidator("http://determined.ai/schemas/expconf/v0/hpc-cluster-slurm.json")
}

func (s SlurmClusterConfigV0) CompletenessValidator() *jsonschema.Schema {
	return schemas.GetCompletenessValidator("http://determined.ai/schemas/expconf/v0/hpc-cluster-slurm.json")
}
