// Code generated by gen.py. DO NOT EDIT.

package expconf

import (
	"github.com/santhosh-tekuri/jsonschema/v2"

	"github.com/determined-ai/determined/master/pkg/schemas"
)

func (g GridConfigV0) GetMetric() string {
	return g.Metric
}

func (g GridConfigV0) GetSmallerIsBetter() bool {
	if g.SmallerIsBetter == nil {
		panic("You must call WithDefaults on GridConfigV0 before .GetSmallerIsBetter")
	}
	return *g.SmallerIsBetter
}

func (g GridConfigV0) GetSourceTrialID() *int {
	return g.SourceTrialID
}

func (g GridConfigV0) GetSourceCheckpointUUID() *string {
	return g.SourceCheckpointUUID
}

func (g GridConfigV0) GetMaxLength() LengthV0 {
	return g.MaxLength
}

func (g GridConfigV0) WithDefaults() GridConfigV0 {
	return schemas.WithDefaults(g).(GridConfigV0)
}

func (g GridConfigV0) Merge(other GridConfigV0) GridConfigV0 {
	return schemas.Merge(g, other).(GridConfigV0)
}

func (g GridConfigV0) ParsedSchema() interface{} {
	return schemas.ParsedGridConfigV0()
}

func (g GridConfigV0) SanityValidator() *jsonschema.Schema {
	return schemas.GetSanityValidator("http://determined.ai/schemas/expconf/v0/searcher-grid.json")
}

func (g GridConfigV0) CompletenessValidator() *jsonschema.Schema {
	return schemas.GetCompletenessValidator("http://determined.ai/schemas/expconf/v0/searcher-grid.json")
}
