// Code generated by stream-gen. DO NOT EDIT.

import { isEqual } from 'lodash';

import { Streamable, StreamSpec } from '.';

export class ProjectSpec extends StreamSpec {
  readonly #id: Streamable = 'projects';
  #workspace_ids: Array<number>;
  #project_ids: Array<number>;
  #since: number;

  constructor(
    workspace_ids?: Array<number>,
    project_ids?: Array<number>,
    since?: number,
  ) {
    super();
    this.#workspace_ids = workspace_ids || [];
    this.#project_ids = project_ids || [];
    this.#since = since || 0;
  }

  public equals = (sp?: StreamSpec): boolean => {
    if (!sp) return false;
    if (sp instanceof ProjectSpec) {
      return (
        isEqual(sp.#workspace_ids, this.#workspace_ids)
        &&
        isEqual(sp.#project_ids, this.#project_ids)
        &&
        isEqual(sp.#since, this.#since)
      );
    }
    return false;
  };

  public id = (): Streamable => {
    return this.#id;
  };

  public toWire = (): Record<string, any> => {
    return { 
      workspace_ids: this.#workspace_ids,
      project_ids: this.#project_ids,
      since: this.#since,
    };
  };
}
