/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The current state of the checkpoint.
 * 
 *  - STATE_UNSPECIFIED: The state of the checkpoint is unknown.
 *  - STATE_ACTIVE: The checkpoint is in an active state.
 *  - STATE_COMPLETED: The checkpoint is persisted to checkpoint storage.
 *  - STATE_ERROR: The checkpoint errored.
 *  - STATE_DELETED: The checkpoint has been deleted.
 * @export
 */
export const Determinedcheckpointv1State = {
    UNSPECIFIED: 'STATE_UNSPECIFIED',
    ACTIVE: 'STATE_ACTIVE',
    COMPLETED: 'STATE_COMPLETED',
    ERROR: 'STATE_ERROR',
    DELETED: 'STATE_DELETED'
} as const;
export type Determinedcheckpointv1State = typeof Determinedcheckpointv1State[keyof typeof Determinedcheckpointv1State];


export function Determinedcheckpointv1StateFromJSON(json: any): Determinedcheckpointv1State {
    return Determinedcheckpointv1StateFromJSONTyped(json, false);
}

export function Determinedcheckpointv1StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Determinedcheckpointv1State {
    return json as Determinedcheckpointv1State;
}

export function Determinedcheckpointv1StateToJSON(value?: Determinedcheckpointv1State | null): any {
    return value as any;
}

