/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create a trial with given hyperparameters.
 * @export
 * @interface V1CreateTrialOperation
 */
export interface V1CreateTrialOperation {
    /**
     * The ID of the trial to create.
     * @type {string}
     * @memberof V1CreateTrialOperation
     */
    requestId?: string;
    /**
     * A JSON object representing the hyperparameters.
     * @type {string}
     * @memberof V1CreateTrialOperation
     */
    hyperparams?: string;
}

/**
 * Check if a given object implements the V1CreateTrialOperation interface.
 */
export function instanceOfV1CreateTrialOperation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1CreateTrialOperationFromJSON(json: any): V1CreateTrialOperation {
    return V1CreateTrialOperationFromJSONTyped(json, false);
}

export function V1CreateTrialOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateTrialOperation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'hyperparams': !exists(json, 'hyperparams') ? undefined : json['hyperparams'],
    };
}

export function V1CreateTrialOperationToJSON(value?: V1CreateTrialOperation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestId': value.requestId,
        'hyperparams': value.hyperparams,
    };
}

