/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response to DeleteProjectRequest.
 * @export
 * @interface V1DeleteProjectResponse
 */
export interface V1DeleteProjectResponse {
    /**
     * Status of deletion.
     * @type {boolean}
     * @memberof V1DeleteProjectResponse
     */
    completed: boolean;
}

/**
 * Check if a given object implements the V1DeleteProjectResponse interface.
 */
export function instanceOfV1DeleteProjectResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "completed" in value;

    return isInstance;
}

export function V1DeleteProjectResponseFromJSON(json: any): V1DeleteProjectResponse {
    return V1DeleteProjectResponseFromJSONTyped(json, false);
}

export function V1DeleteProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeleteProjectResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completed': json['completed'],
    };
}

export function V1DeleteProjectResponseToJSON(value?: V1DeleteProjectResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completed': value.completed,
    };
}

