/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Pagination } from './V1Pagination';
import {
    V1PaginationFromJSON,
    V1PaginationFromJSONTyped,
    V1PaginationToJSON,
} from './V1Pagination';
import type { V1User } from './V1User';
import {
    V1UserFromJSON,
    V1UserFromJSONTyped,
    V1UserToJSON,
} from './V1User';

/**
 * Response to GetUsersRequest.
 * @export
 * @interface V1GetUsersResponse
 */
export interface V1GetUsersResponse {
    /**
     * The list of requested users.
     * @type {Array<V1User>}
     * @memberof V1GetUsersResponse
     */
    users?: Array<V1User>;
    /**
     * 
     * @type {V1Pagination}
     * @memberof V1GetUsersResponse
     */
    pagination?: V1Pagination;
}

/**
 * Check if a given object implements the V1GetUsersResponse interface.
 */
export function instanceOfV1GetUsersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetUsersResponseFromJSON(json: any): V1GetUsersResponse {
    return V1GetUsersResponseFromJSONTyped(json, false);
}

export function V1GetUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(V1UserFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : V1PaginationFromJSON(json['pagination']),
    };
}

export function V1GetUsersResponseToJSON(value?: V1GetUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users === undefined ? undefined : ((value.users as Array<any>).map(V1UserToJSON)),
        'pagination': V1PaginationToJSON(value.pagination),
    };
}

