/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1TrialOperation } from './V1TrialOperation';
import {
    V1TrialOperationFromJSON,
    V1TrialOperationFromJSONTyped,
    V1TrialOperationToJSON,
} from './V1TrialOperation';

/**
 * 
 * @export
 * @interface V1GetCurrentTrialSearcherOperationResponse
 */
export interface V1GetCurrentTrialSearcherOperationResponse {
    /**
     * 
     * @type {V1TrialOperation}
     * @memberof V1GetCurrentTrialSearcherOperationResponse
     */
    op?: V1TrialOperation;
    /**
     * The status of the searcher operation.
     * @type {boolean}
     * @memberof V1GetCurrentTrialSearcherOperationResponse
     */
    completed?: boolean;
}

/**
 * Check if a given object implements the V1GetCurrentTrialSearcherOperationResponse interface.
 */
export function instanceOfV1GetCurrentTrialSearcherOperationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetCurrentTrialSearcherOperationResponseFromJSON(json: any): V1GetCurrentTrialSearcherOperationResponse {
    return V1GetCurrentTrialSearcherOperationResponseFromJSONTyped(json, false);
}

export function V1GetCurrentTrialSearcherOperationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetCurrentTrialSearcherOperationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'op': !exists(json, 'op') ? undefined : V1TrialOperationFromJSON(json['op']),
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
    };
}

export function V1GetCurrentTrialSearcherOperationResponseToJSON(value?: V1GetCurrentTrialSearcherOperationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'op': V1TrialOperationToJSON(value.op),
        'completed': value.completed,
    };
}

