/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Pagination } from './V1Pagination';
import {
    V1PaginationFromJSON,
    V1PaginationFromJSONTyped,
    V1PaginationToJSON,
} from './V1Pagination';
import type { V1Tensorboard } from './V1Tensorboard';
import {
    V1TensorboardFromJSON,
    V1TensorboardFromJSONTyped,
    V1TensorboardToJSON,
} from './V1Tensorboard';

/**
 * Response to GetTensorboardsRequest.
 * @export
 * @interface V1GetTensorboardsResponse
 */
export interface V1GetTensorboardsResponse {
    /**
     * The list of returned tensorboards.
     * @type {Array<V1Tensorboard>}
     * @memberof V1GetTensorboardsResponse
     */
    tensorboards?: Array<V1Tensorboard>;
    /**
     * 
     * @type {V1Pagination}
     * @memberof V1GetTensorboardsResponse
     */
    pagination?: V1Pagination;
}

/**
 * Check if a given object implements the V1GetTensorboardsResponse interface.
 */
export function instanceOfV1GetTensorboardsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetTensorboardsResponseFromJSON(json: any): V1GetTensorboardsResponse {
    return V1GetTensorboardsResponseFromJSONTyped(json, false);
}

export function V1GetTensorboardsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetTensorboardsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tensorboards': !exists(json, 'tensorboards') ? undefined : ((json['tensorboards'] as Array<any>).map(V1TensorboardFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : V1PaginationFromJSON(json['pagination']),
    };
}

export function V1GetTensorboardsResponseToJSON(value?: V1GetTensorboardsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tensorboards': value.tensorboards === undefined ? undefined : ((value.tensorboards as Array<any>).map(V1TensorboardToJSON)),
        'pagination': V1PaginationToJSON(value.pagination),
    };
}

