/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sorts agents by the given field.
 * 
 *  - SORT_BY_UNSPECIFIED: Returns agents in an unsorted list.
 *  - SORT_BY_ID: Returns agents sorted by id.
 *  - SORT_BY_TIME: Returns agents sorted by time.
 * @export
 * @enum {string}
 */
export enum V1GetAgentsRequestSortBy {
    Unspecified = 'SORT_BY_UNSPECIFIED',
    Id = 'SORT_BY_ID',
    Time = 'SORT_BY_TIME'
}


export function V1GetAgentsRequestSortByFromJSON(json: any): V1GetAgentsRequestSortBy {
    return V1GetAgentsRequestSortByFromJSONTyped(json, false);
}

export function V1GetAgentsRequestSortByFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetAgentsRequestSortBy {
    return json as V1GetAgentsRequestSortBy;
}

export function V1GetAgentsRequestSortByToJSON(value?: V1GetAgentsRequestSortBy | null): any {
    return value as any;
}

