/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetRolesByIDRequest
 */
export interface V1GetRolesByIDRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof V1GetRolesByIDRequest
     */
    roleIds?: Array<number>;
}

/**
 * Check if a given object implements the V1GetRolesByIDRequest interface.
 */
export function instanceOfV1GetRolesByIDRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetRolesByIDRequestFromJSON(json: any): V1GetRolesByIDRequest {
    return V1GetRolesByIDRequestFromJSONTyped(json, false);
}

export function V1GetRolesByIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetRolesByIDRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleIds': !exists(json, 'roleIds') ? undefined : json['roleIds'],
    };
}

export function V1GetRolesByIDRequestToJSON(value?: V1GetRolesByIDRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roleIds': value.roleIds,
    };
}

