/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Command } from './V1Command';
import {
    V1CommandFromJSON,
    V1CommandFromJSONTyped,
    V1CommandToJSON,
} from './V1Command';

/**
 * Response to GetCommandRequest.
 * @export
 * @interface V1GetCommandResponse
 */
export interface V1GetCommandResponse {
    /**
     * 
     * @type {V1Command}
     * @memberof V1GetCommandResponse
     */
    command?: V1Command;
    /**
     * The command config.
     * @type {object}
     * @memberof V1GetCommandResponse
     */
    config?: object;
}

/**
 * Check if a given object implements the V1GetCommandResponse interface.
 */
export function instanceOfV1GetCommandResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetCommandResponseFromJSON(json: any): V1GetCommandResponse {
    return V1GetCommandResponseFromJSONTyped(json, false);
}

export function V1GetCommandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetCommandResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'command': !exists(json, 'command') ? undefined : V1CommandFromJSON(json['command']),
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function V1GetCommandResponseToJSON(value?: V1GetCommandResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'command': V1CommandToJSON(value.command),
        'config': value.config,
    };
}

