/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1SearcherEvent } from './V1SearcherEvent';
import {
    V1SearcherEventFromJSON,
    V1SearcherEventFromJSONTyped,
    V1SearcherEventToJSON,
} from './V1SearcherEvent';

/**
 * Response to GetSearcherEventsRequest.
 * @export
 * @interface V1GetSearcherEventsResponse
 */
export interface V1GetSearcherEventsResponse {
    /**
     * The list of events in the queue.
     * @type {Array<V1SearcherEvent>}
     * @memberof V1GetSearcherEventsResponse
     */
    searcherEvents?: Array<V1SearcherEvent>;
}

/**
 * Check if a given object implements the V1GetSearcherEventsResponse interface.
 */
export function instanceOfV1GetSearcherEventsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetSearcherEventsResponseFromJSON(json: any): V1GetSearcherEventsResponse {
    return V1GetSearcherEventsResponseFromJSONTyped(json, false);
}

export function V1GetSearcherEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetSearcherEventsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searcherEvents': !exists(json, 'searcherEvents') ? undefined : ((json['searcherEvents'] as Array<any>).map(V1SearcherEventFromJSON)),
    };
}

export function V1GetSearcherEventsResponseToJSON(value?: V1GetSearcherEventsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'searcherEvents': value.searcherEvents === undefined ? undefined : ((value.searcherEvents as Array<any>).map(V1SearcherEventToJSON)),
    };
}

