/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Metrics
 */
export interface V1Metrics {
    /**
     * 
     * @type {object}
     * @memberof V1Metrics
     */
    avgMetrics: object;
    /**
     * 
     * @type {Array<object>}
     * @memberof V1Metrics
     */
    batchMetrics?: Array<object>;
}

/**
 * Check if a given object implements the V1Metrics interface.
 */
export function instanceOfV1Metrics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "avgMetrics" in value;

    return isInstance;
}

export function V1MetricsFromJSON(json: any): V1Metrics {
    return V1MetricsFromJSONTyped(json, false);
}

export function V1MetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Metrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avgMetrics': json['avgMetrics'],
        'batchMetrics': !exists(json, 'batchMetrics') ? undefined : json['batchMetrics'],
    };
}

export function V1MetricsToJSON(value?: V1Metrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avgMetrics': value.avgMetrics,
        'batchMetrics': value.batchMetrics,
    };
}

