/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request to move an experiment into a project.
 * @export
 * @interface V1MoveExperimentRequest
 */
export interface V1MoveExperimentRequest {
    /**
     * The id of the experiment being moved.
     * @type {number}
     * @memberof V1MoveExperimentRequest
     */
    experimentId: number;
    /**
     * The id of the new parent project.
     * @type {number}
     * @memberof V1MoveExperimentRequest
     */
    destinationProjectId: number;
}

/**
 * Check if a given object implements the V1MoveExperimentRequest interface.
 */
export function instanceOfV1MoveExperimentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "experimentId" in value;
    isInstance = isInstance && "destinationProjectId" in value;

    return isInstance;
}

export function V1MoveExperimentRequestFromJSON(json: any): V1MoveExperimentRequest {
    return V1MoveExperimentRequestFromJSONTyped(json, false);
}

export function V1MoveExperimentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MoveExperimentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experimentId': json['experimentId'],
        'destinationProjectId': json['destinationProjectId'],
    };
}

export function V1MoveExperimentRequestToJSON(value?: V1MoveExperimentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experimentId': value.experimentId,
        'destinationProjectId': value.destinationProjectId,
    };
}

