/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Checkpoint } from './V1Checkpoint';
import {
    V1CheckpointFromJSON,
    V1CheckpointFromJSONTyped,
    V1CheckpointToJSON,
} from './V1Checkpoint';

/**
 * Response to PostCheckpointRequest.
 * @export
 * @interface V1PostCheckpointMetadataResponse
 */
export interface V1PostCheckpointMetadataResponse {
    /**
     * 
     * @type {V1Checkpoint}
     * @memberof V1PostCheckpointMetadataResponse
     */
    checkpoint?: V1Checkpoint;
}

/**
 * Check if a given object implements the V1PostCheckpointMetadataResponse interface.
 */
export function instanceOfV1PostCheckpointMetadataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1PostCheckpointMetadataResponseFromJSON(json: any): V1PostCheckpointMetadataResponse {
    return V1PostCheckpointMetadataResponseFromJSONTyped(json, false);
}

export function V1PostCheckpointMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PostCheckpointMetadataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkpoint': !exists(json, 'checkpoint') ? undefined : V1CheckpointFromJSON(json['checkpoint']),
    };
}

export function V1PostCheckpointMetadataResponseToJSON(value?: V1PostCheckpointMetadataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkpoint': V1CheckpointToJSON(value.checkpoint),
    };
}

