/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Timestamp filters.
 * @export
 * @interface V1TimestampFieldFilter
 */
export interface V1TimestampFieldFilter {
    /**
     * Less than.
     * @type {Date}
     * @memberof V1TimestampFieldFilter
     */
    lt?: Date;
    /**
     * Less than or equal.
     * @type {Date}
     * @memberof V1TimestampFieldFilter
     */
    lte?: Date;
    /**
     * Greater than.
     * @type {Date}
     * @memberof V1TimestampFieldFilter
     */
    gt?: Date;
    /**
     * Greater than or equal.
     * @type {Date}
     * @memberof V1TimestampFieldFilter
     */
    gte?: Date;
}

/**
 * Check if a given object implements the V1TimestampFieldFilter interface.
 */
export function instanceOfV1TimestampFieldFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1TimestampFieldFilterFromJSON(json: any): V1TimestampFieldFilter {
    return V1TimestampFieldFilterFromJSONTyped(json, false);
}

export function V1TimestampFieldFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TimestampFieldFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lt': !exists(json, 'lt') ? undefined : (new Date(json['lt'])),
        'lte': !exists(json, 'lte') ? undefined : (new Date(json['lte'])),
        'gt': !exists(json, 'gt') ? undefined : (new Date(json['gt'])),
        'gte': !exists(json, 'gte') ? undefined : (new Date(json['gte'])),
    };
}

export function V1TimestampFieldFilterToJSON(value?: V1TimestampFieldFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lt': value.lt === undefined ? undefined : (value.lt.toISOString()),
        'lte': value.lte === undefined ? undefined : (value.lte.toISOString()),
        'gt': value.gt === undefined ? undefined : (value.gt.toISOString()),
        'gte': value.gte === undefined ? undefined : (value.gte.toISOString()),
    };
}

