/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1TrialEarlyExitExitedReason } from './V1TrialEarlyExitExitedReason';
import {
    V1TrialEarlyExitExitedReasonFromJSON,
    V1TrialEarlyExitExitedReasonFromJSONTyped,
    V1TrialEarlyExitExitedReasonToJSON,
} from './V1TrialEarlyExitExitedReason';

/**
 * Signals to the experiment the trial early exited.
 * @export
 * @interface V1TrialEarlyExit
 */
export interface V1TrialEarlyExit {
    /**
     * 
     * @type {V1TrialEarlyExitExitedReason}
     * @memberof V1TrialEarlyExit
     */
    reason: V1TrialEarlyExitExitedReason;
}

/**
 * Check if a given object implements the V1TrialEarlyExit interface.
 */
export function instanceOfV1TrialEarlyExit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function V1TrialEarlyExitFromJSON(json: any): V1TrialEarlyExit {
    return V1TrialEarlyExitFromJSONTyped(json, false);
}

export function V1TrialEarlyExitFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TrialEarlyExit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': V1TrialEarlyExitExitedReasonFromJSON(json['reason']),
    };
}

export function V1TrialEarlyExitToJSON(value?: V1TrialEarlyExit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': V1TrialEarlyExitExitedReasonToJSON(value.reason),
    };
}

