/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response to TrialLogFieldsRequest.
 * @export
 * @interface V1TrialLogsFieldsResponse
 */
export interface V1TrialLogsFieldsResponse {
    /**
     * The distinct agent IDs present in the logs.
     * @type {Array<string>}
     * @memberof V1TrialLogsFieldsResponse
     */
    agentIds?: Array<string>;
    /**
     * The distinct container IDs present in the logs.
     * @type {Array<string>}
     * @memberof V1TrialLogsFieldsResponse
     */
    containerIds?: Array<string>;
    /**
     * The distinct rank IDs present in the logs.
     * @type {Array<number>}
     * @memberof V1TrialLogsFieldsResponse
     */
    rankIds?: Array<number>;
    /**
     * The distinct stdtypes present in the logs.
     * @type {Array<string>}
     * @memberof V1TrialLogsFieldsResponse
     */
    stdtypes?: Array<string>;
    /**
     * The distinct sources present in the logs.
     * @type {Array<string>}
     * @memberof V1TrialLogsFieldsResponse
     */
    sources?: Array<string>;
}

/**
 * Check if a given object implements the V1TrialLogsFieldsResponse interface.
 */
export function instanceOfV1TrialLogsFieldsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1TrialLogsFieldsResponseFromJSON(json: any): V1TrialLogsFieldsResponse {
    return V1TrialLogsFieldsResponseFromJSONTyped(json, false);
}

export function V1TrialLogsFieldsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TrialLogsFieldsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agentIds': !exists(json, 'agentIds') ? undefined : json['agentIds'],
        'containerIds': !exists(json, 'containerIds') ? undefined : json['containerIds'],
        'rankIds': !exists(json, 'rankIds') ? undefined : json['rankIds'],
        'stdtypes': !exists(json, 'stdtypes') ? undefined : json['stdtypes'],
        'sources': !exists(json, 'sources') ? undefined : json['sources'],
    };
}

export function V1TrialLogsFieldsResponseToJSON(value?: V1TrialLogsFieldsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agentIds': value.agentIds,
        'containerIds': value.containerIds,
        'rankIds': value.rankIds,
        'stdtypes': value.stdtypes,
        'sources': value.sources,
    };
}

