/* tslint:disable */
/* eslint-disable */
/**
 * Determined API (Beta)
 * Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@determined.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1GroupDetails } from './V1GroupDetails';
import {
    V1GroupDetailsFromJSON,
    V1GroupDetailsFromJSONTyped,
    V1GroupDetailsToJSON,
} from './V1GroupDetails';

/**
 * UpdateGroupResponse is the body of the response for the call
 * to update a group and its members.
 * @export
 * @interface V1UpdateGroupResponse
 */
export interface V1UpdateGroupResponse {
    /**
     * 
     * @type {V1GroupDetails}
     * @memberof V1UpdateGroupResponse
     */
    group: V1GroupDetails;
}

/**
 * Check if a given object implements the V1UpdateGroupResponse interface.
 */
export function instanceOfV1UpdateGroupResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "group" in value;

    return isInstance;
}

export function V1UpdateGroupResponseFromJSON(json: any): V1UpdateGroupResponse {
    return V1UpdateGroupResponseFromJSONTyped(json, false);
}

export function V1UpdateGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateGroupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': V1GroupDetailsFromJSON(json['group']),
    };
}

export function V1UpdateGroupResponseToJSON(value?: V1UpdateGroupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': V1GroupDetailsToJSON(value.group),
    };
}

