# coding: utf-8

"""
    Determined API (Beta)

    Determined helps deep learning teams train models more quickly, easily share GPU resources, and effectively collaborate. Determined allows deep learning engineers to focus on building and training models at scale, without needing to worry about DevOps or writing custom code for common tasks like fault tolerance or experiment tracking.  You can think of Determined as a platform that bridges the gap between tools like TensorFlow and PyTorch --- which work great for a single researcher with a single GPU --- to the challenges that arise when doing deep learning at scale, as teams, clusters, and data sets all increase in size.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: community@determined.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1TrainingUnits(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unit': 'V1Unit',
        'count': 'int'
    }

    attribute_map = {
        'unit': 'unit',
        'count': 'count'
    }

    def __init__(self, unit=None, count=None):  # noqa: E501
        """V1TrainingUnits - a model defined in Swagger"""  # noqa: E501

        self._unit = None
        self._count = None
        self.discriminator = None

        if unit is not None:
            self.unit = unit
        if count is not None:
            self.count = count

    @property
    def unit(self):
        """Gets the unit of this V1TrainingUnits.  # noqa: E501

        This is the unit the TrainingLength is in terms of.  # noqa: E501

        :return: The unit of this V1TrainingUnits.  # noqa: E501
        :rtype: V1Unit
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this V1TrainingUnits.

        This is the unit the TrainingLength is in terms of.  # noqa: E501

        :param unit: The unit of this V1TrainingUnits.  # noqa: E501
        :type: V1Unit
        """

        self._unit = unit

    @property
    def count(self):
        """Gets the count of this V1TrainingUnits.  # noqa: E501

        This is the magnitude of the TrainingLength.  # noqa: E501

        :return: The count of this V1TrainingUnits.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this V1TrainingUnits.

        This is the magnitude of the TrainingLength.  # noqa: E501

        :param count: The count of this V1TrainingUnits.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1TrainingUnits, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1TrainingUnits):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
