-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module DetQL.Enum.Steps_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "steps"

  - End\_time - column name
  - Id - column name
  - Metrics - column name
  - Start\_time - column name
  - State - column name
  - Trial\_id - column name

-}
type Steps_select_column
    = End_time
    | Id
    | Metrics
    | Start_time
    | State
    | Trial_id


list : List Steps_select_column
list =
    [ End_time, Id, Metrics, Start_time, State, Trial_id ]


decoder : Decoder Steps_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "end_time" ->
                        Decode.succeed End_time

                    "id" ->
                        Decode.succeed Id

                    "metrics" ->
                        Decode.succeed Metrics

                    "start_time" ->
                        Decode.succeed Start_time

                    "state" ->
                        Decode.succeed State

                    "trial_id" ->
                        Decode.succeed Trial_id

                    _ ->
                        Decode.fail ("Invalid Steps_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Steps_select_column -> String
toString enum =
    case enum of
        End_time ->
            "end_time"

        Id ->
            "id"

        Metrics ->
            "metrics"

        Start_time ->
            "start_time"

        State ->
            "state"

        Trial_id ->
            "trial_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Steps_select_column
fromString enumString =
    case enumString of
        "end_time" ->
            Just End_time

        "id" ->
            Just Id

        "metrics" ->
            Just Metrics

        "start_time" ->
            Just Start_time

        "state" ->
            Just State

        "trial_id" ->
            Just Trial_id

        _ ->
            Nothing
