"""
This file is the configuration file for the Sphinx documentation builder.
See the documentation: http://www.sphinx-doc.org/en/master/config
"""

import os
import pathlib
import sys

# Doc Path
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

project = "Determined"
html_title = "Determined AI Documentation"
copyright = "2022, Determined AI"
author = "hello@determined.ai"
version = pathlib.Path(__file__).parents[1].joinpath("VERSION").read_text()
release = version
language = "en"

source_suffix = {".rst": "restructuredtext", ".txt": "restructuredtext"}
templates_path = ["_templates"]
html_static_path = ["assets"]
html_css_files = [
    'styles/determined.css',
]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "examples",
    "requirements.txt",
    "site",
]
html_baseurl = "https://docs.determined.ai"  # Base URL for sitemap.
highlight_language = "none"
todo_include_todos = True

# HTML theme settings
html_show_sourcelink = False
html_show_sphinx = False
html_theme = "furo"
html_favicon = "assets/images/favicon.ico"
html_last_updated_fmt = None
# See https://pradyunsg.me/furo/

html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar-version.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
    ]
}

pygments_style = "sphinx"
pygments_dark_style = "monokai"
html_theme_options = {
    "light_logo": "images/logo-determined-ai.svg",
    "dark_logo": "images/logo-determined-ai-white.svg",
    "sidebar_hide_name": True,
    "light_css_variables": {
        "color-brand-primary": "#f37a22",
        "color-brand-content": "#f37a22",
        "font-stack": "Open Sans, Metric HPE, Arial, sans-serif",
    },
    "dark_css_variables": {
        "color-brand-primary": "#f37a22",
        "color-brand-content": "#f37a22",
    },
}
html_use_index = True
html_domain_indices = True

extensions = [
    "sphinx_ext_downloads",
    "sphinx.ext.autodoc",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx_copybutton",
    "sphinx_sitemap",
    "sphinx_reredirects",
]

# Our custom sphinx extension uses this value to decide where to look for
# downloadable files.
dai_downloads_root = os.path.join("site", "downloads")

# sphinx.ext.autodoc configurations.
# See https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
autosummary_generate = True
autoclass_content = "class"
autodoc_mock_imports = [
    "mmcv",
    "mmdet",
    "transformers",
    "pytorch_lightning",
    "deepspeed",
    "datasets",
    "analytics",
]

# sphinx-sitemap configurations.
# See https://github.com/jdillard/sphinx-sitemap
# The URLs generated by sphinx-sitemap include both the version number and the
# language by default. We don't use language in the published URL, and we also
# want to encourage the latest version of the docs to be indexed, so only
# include that variant in the sitemap.
sitemap_url_scheme = "latest/{link}"

redirects = {
    "tutorials/quick-start": "../getting-started.html",
}
