"""
This file is the configuration file for the Sphinx documentation builder.
See the documentation: http://www.sphinx-doc.org/en/master/config
"""

import os
import pathlib
import sys

# Doc Path
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

project = "Determined"
html_title = "Determined AI Documentation"
copyright = "2020, Determined AI"
author = "hello@determined.ai"
version = pathlib.Path(__file__).parents[1].joinpath("VERSION").read_text()
release = version
language = "en"

source_suffix = {".rst": "restructuredtext", ".txt": "restructuredtext"}
templates_path = ["_templates"]
html_static_path = ["assets"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "examples", "requirements.txt", "site"]
html_baseurl = "https://docs.determined.ai" # Base URL for sitemap.
highlight_language = "none"
todo_include_todos = True

# HTML theme settings
html_show_sourcelink = False
html_show_sphinx = False
html_theme = "furo"
html_favicon = "assets/images/favicon.ico"
html_last_updated_fmt = None
# See https://pradyunsg.me/furo/
html_sidebars = {"**": [
    "sidebar/scroll-start.html",
    "sidebar/brand.html",
    "sidebar-version.html",
    "sidebar/search.html",
    "sidebar/navigation.html",
    "sidebar/ethical-ads.html",
    "sidebar/scroll-end.html",
]}
pygments_style = "sphinx"
pygments_dark_style = "monokai"
html_theme_options = {
    "light_logo": "images/logo-determined-ai.svg",
    "dark_logo": "images/logo-determined-ai-white.svg",
    "sidebar_hide_name": True,
    "light_css_variables": {
        "color-brand-primary": "#f37a22",
        "color-brand-content": "#f37a22",
    },
    "dark_css_variables": {
        "color-brand-primary": "#f37a22",
        "color-brand-content": "#f37a22",
    },
}
html_use_index = True
html_domain_indices = True

extensions = [
    "sphinx_ext_downloads",
    "sphinx.ext.autodoc",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx_copybutton",
    "sphinx_sitemap",
    "sphinx_reredirects",
]

# Our custom sphinx extension uses this value to decide where to look for
# downloadable files.
dai_downloads_root = os.path.join("site", "downloads")

# sphinx.ext.autodoc configurations.
# See https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
autosummary_generate = True
autoclass_content = "class"
autodoc_mock_imports = [
    "mmcv", "mmdet", "transformers", "pytorch_lightning", "datasets", "analytics",
]

# sphinx-sitemap configurations.
# See https://github.com/jdillard/sphinx-sitemap
# The URLs generated by sphinx-sitemap include both the version number and the
# language by default. We don't use language in the published URL, and we also
# want to encourage the latest version of the docs to be indexed, so only
# include that variant in the sitemap.
sitemap_url_scheme = "latest/{link}"

redirects = {
    "tutorials/quick-start": "../getting-started.html",
    "tutorials/model-registry": "../post-training/model-registry.html",
    "tutorials/data-access": "../prepare-data/index.html",
    "tutorials/porting-tutorial": "../tutorials/index.html",
    "tutorials/notebook-tutorial": "../features/notebooks.html",
    "topic-guides/index": "../index.html",
    "topic-guides/benefits-of-determined": "../features/index.html",
    "topic-guides/cluster-configuration/oauth": "../../sysadmin-basics/oauth.html",
    "topic-guides/cluster-configuration/saml": "../../sysadmin-basics/saml.html",
    "topic-guides/cluster-configuration/scim": "../../sysadmin-basics/scim.html",
    "topic-guides/cluster-configuration/tls": "../../sysadmin-basics/tls.html",
    "topic-guides/cluster-configuration/users": "../../sysadmin-basics/users.html",
    "topic-guides/oauth": "../sysadmin-basics/oauth.html",
    "topic-guides/saml": "../sysadmin-basics/saml.html",
    "topic-guides/scim": "../sysadmin-basics/scim.html",
    "topic-guides/tls": "../sysadmin-basics/tls.html",
    "topic-guides/users": "../sysadmin-basics/users.html",
    "topic-guides/cluster-configuration/elasticsearch-logging-backend": "../../sysadmin-basics/elasticsearch-logging-backend.html",
    "topic-guides/commands-and-shells": "../features/commands-and-shells.html",
    "topic-guides/deployment/aws-spot": "../../sysadmin-deploy-on-aws/aws-spot.html",
    "topic-guides/deployment/aws": "../../sysadmin-deploy-on-aws/index.html",
    "topic-guides/deployment/gcp": "../../sysadmin-deploy-on-gcp/index.html",
    "topic-guides/deployment/determined-on-kubernetes": "../../sysadmin-deploy-on-k8s/index.html",
    "topic-guides/distributed-training/optimizing-distributed-training": "../../training-distributed/index.html",
    "topic-guides/distributed-training/effective-distributed-training": "../../training-distributed/effective-distributed-training.html",
    "topic-guides/hp-tuning-det/index": "../../training-hyperparameter/index.html",
    "topic-guides/model-definitions/index": "../../training-apis/index.html",
    "topic-guides/model-definitions/trial-api": "../../training-apis/index.html",
    "topic-guides/model-definitions/best-practices": "../../training-apis/index.html",
    "topic-guides/system-concepts/elastic-infrastructure": "../../features/elastic-infrastructure.html",
    "topic-guides/system-concepts/resource-pool": "../../concepts/resource-pool.html",
    "topic-guides/system-concepts/scheduling": "../../concepts/scheduling.html",
    "topic-guides/system-concepts/system-architecture": "../../features/system-architecture.html",
    "topic-guides/system-concepts/terminology-concepts": "../../features/terminology-concepts.html",
    "topic-guides/training/experiment-lifecycle": "../../training-run/index.html",
    "topic-guides/user-interfaces": "../interact/index.html",
    "topic-guides/yaml": "../concepts/yaml.html",
    "topic-guides/checkpoints": "../training-apis/index.html",
    "topic-guides/hp-tuning-det/hp-adaptive-asha": "../../training-hyperparameter/hp-adaptive-asha.html",
    "topic-guides/hp-tuning-det/hp-constraints-det": "../../training-hyperparameter/hp-constraints-det.html",
    "topic-guides/hp-constraints-det": "../training-hyperparameter/hp-constraints-det.html",
    "topic-guides/hp-tuning-det/hp-grid": "../../training-hyperparameter/hp-grid.html",
    "topic-guides/hp-tuning-det/hp-pbt": "../../training-hyperparameter/hp-pbt.html",
    "topic-guides/hp-tuning-det/hp-random": "../../training-hyperparameter/hp-random.html",
    "topic-guides/hp-tuning-det/hp-single": "../../training-hyperparameter/hp-single.html",
    "topic-guides/hp-tuning-det/hp-tuning-defined": "../../training-hyperparameter/hp-tuning-defined.html",
    "topic-guides/hp-tuning-defined": "../training-hyperparameter/hp-tuning-defined.html",
    "topic-guides/training/training-units": "../../training-apis/experiment-config.html",
    "topic-guides/training/reproducibility": "../../training-reproducibility/index.html",
    "how-to/index": "../index.html",
    "how-to/notebooks": "../features/notebooks.html",
    "how-to/tensorboard": "../features/tensorboard.html",
    "how-to/distributed-training": "../training-distributed/index.html",
    "how-to/hyperparameter-tuning": "../training-hyperparameter/index.html",
    "how-to/install-cli": "../interact/cli.html",
    "how-to/install-main": "../sysadmin-basics/index.html",
    "how-to/rest-apis": "../interact/rest-apis.html",
    "how-to/use-trained-models": "../post-training/use-trained-models.html",
    "how-to/data-layer": "../training-apis/data-layer.html",
    "how-to/custom-env": "../prepare-environment/custom-env.html",
    "how-to/model-debug": "../training-debug/index.html",
    "how-to/profiling": "../training-debug/profiling.html",
    "how-to/installation/custom-pod-specs": "../../prepare-environment/custom-pod-specs.html",
    "how-to/installation/network-requirements": "../../sysadmin-basics/network-requirements.html",
    "how-to/installation/upgrades-troubleshoot": "../../sysadmin-basics/upgrades-troubleshoot.html",
    "how-to/installation/dynamic-agents-aws": "../../sysadmin-deploy-on-aws/dynamic-agents-aws.html",
    "how-to/installation/aws": "../../sysadmin-deploy-on-aws/install-on-aws.html",
    "how-to/installation/gcp": "../../sysadmin-deploy-on-gcp/install-on-gcp.html",
    "how-to/installation/dynamic-agents-gcp": "../../sysadmin-deploy-on-gcp/dynamic-agents-gcp.html",
    "how-to/installation/setup-aks-cluster": "../../sysadmin-deploy-on-k8s/setup-aks-cluster.html",
    "how-to/installation/setup-eks-cluster": "../../sysadmin-deploy-on-k8s/setup-eks-cluster.html",
    "how-to/installation/setup-gke-cluster": "../../sysadmin-deploy-on-k8s/setup-gke-cluster.html",
    "how-to/installation/kubernetes": "../../sysadmin-deploy-on-k8s/install-on-kubernetes.html",
    "how-to/installation/k8s-dev-guide": "../../sysadmin-deploy-on-k8s/k8s-dev-guide.html",
    "how-to/installation/deploy": "../../sysadmin-deploy-on-prem/deploy.html",
    "how-to/installation/docker": "../../sysadmin-deploy-on-prem/docker.html",
    "how-to/installation/linux-packages": "../../sysadmin-deploy-on-prem/linux-packages.html",
    "how-to/installation/requirements": "../../sysadmin-deploy-on-prem/requirements.html",
    "reference/index": "../index.html",
    "reference/api/config-template": "../../features/config-template.html",
    "reference/config-template": "../features/config-template.html",
    "reference/api/command-notebook-config": "../../features/command-notebook-config.html",
    "reference/command-notebook-config": "../features/command-notebook-config.html",
    "reference/api/api-experimental-client.txt": "../../interact/api-experimental-client.html",
    "reference/api/api-pytorch-samplers": "../../training-apis/api-pytorch.html",
    "reference/api/api-determined": "../../training-apis/index.html",
    "reference/api/api-estimator": "../../training-apis/api-estimator.html",
    "reference/api/api-keras": "../../training-apis/api-keras.html",
    "reference/api/api-pytorch": "../../training-apis/api-pytorch.html",
    "reference/api/api-pytorch-lightning": "../../training-apis/api-pytorch-lightning.html",
    "reference/api/api-trial_context": "../../training-apis/index.html",
    "reference/api/experiment-config": "../../training-apis/experiment-config.html",
    "reference/experiment-config": "../training-apis/experiment-config.html",
    "reference/cli": "../interact/cli.html",
    "reference/rest-api": "../interact/rest-apis.html",
    "reference/cluster/cluster-config": "../../sysadmin-basics/cluster-config.html",
    "reference/cluster-config": "../sysadmin-basics/cluster-config.html",
    "reference/cluster/historical-cluster-usage-data": "../../sysadmin-basics/historical-cluster-usage-data.html",
    "reference/historical-cluster-usage-data": "../sysadmin-basics/historical-cluster-usage-data.html",
    "reference/cluster/helm-config": "../../sysadmin-deploy-on-k8s/helm-config.html",
    "reference/helm-config": "../sysadmin-deploy-on-k8s/helm-config.html",
    "reference/attributions": "../attributions.html",
    "features/index": "../concepts/index.html",
    "features/experiments": "../training-run/index.html",
    "features/resource-pool": "../concepts/resource-pool.html",
    "features/scheduling": "../concepts/scheduling.html",
    "features/system-architecture": "../concepts/index.html",
    "features/terminology-concepts": "../concepts/index.html",
    "features/yaml": "../concepts/yaml.html",
    "prepare-data/data-layer": "../training-apis/data-layer.html",
    "training-apis/api-determined": "index.html",
    "training-apis/api-pytorch-samplers": "api-pytorch.html#reproducible-dataset",
    "training-apis/api-trial_context": "index.html",
    "training-apis/best-practices-for-model-definitions": "index.html",
    "training-apis/examples": "examples.html",
    "training-apis/faq": "index.html",
    "training-apis/save-checkpoints": "experiment-config.html",
    "training-apis/training-units": "experiment-config.html",
    "training-apis/trial-api": "index.html",
}
